steps:
- id: 'Provision GWS Components'
  name: 'gcr.io/gcpe0003/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-gws.sh']
  secretEnv: ['PULLSECRET','JFROGPASS','JFROGUSR','DB_NAME','LOCATION','POSTGRES_ADDR','POSTGRES_PASSWORD','POSTGRES_USER','gws_ops_pass_encr','gws_ops_user','DB_NAME_PROV',
              'gauth_admin_password','gauth_admin_password_plain','gws_client_id','gws_client_secret','gws_pg_user','DB_NAME_GWS','gws_app_provisioning','gws_app_workspace','gws_as_pg_pass','gws_as_pg_user','gws_pg_pass']
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
  timeout: '3600s'
availableSecrets:
  secretManager:
  - versionName: "projects/402866575973/secrets/PULLSECRET/versions/1"
    env: 'PULLSECRET'
  - versionName: "projects/402866575973/secrets/JFROGUSR/versions/1"
    env: "JFROGUSR"
  - versionName: "projects/402866575973/secrets/JFROGPASS/versions/1"
    env: "JFROGPASS"
  - versionName: "projects/402866575973/secrets/DB_NAME/versions/1"
    env: "DB_NAME"
  - versionName: "projects/402866575973/secrets/LOCATION/versions/1"
    env:  "LOCATION"
  - versionName: "projects/402866575973/secrets/POSTGRES_ADDR_GWS/versions/1"
    env:  "POSTGRES_ADDR"
  - versionName: "projects/402866575973/secrets/POSTGRES_PASSWORD/versions/1"
    env:  "POSTGRES_PASSWORD"
  - versionName: "projects/402866575973/secrets/POSTGRES_USER/versions/1"
    env:  "POSTGRES_USER"  
  - versionName: "projects/402866575973/secrets/gws_app_provisioning/versions/1"
    env:  "gws_app_provisioning"
  - versionName: "projects/402866575973/secrets/gws_app_workspace/versions/1"
    env:  "gws_app_workspace"
  - versionName: "projects/402866575973/secrets/gws_as_pg_pass/versions/1"
    env:  "gws_as_pg_pass"
  - versionName: "projects/402866575973/secrets/gws_as_pg_user/versions/1"
    env:  "gws_as_pg_user"
  - versionName: "projects/402866575973/secrets/gws_client_id/versions/1"
    env:  "gws_client_id"
  - versionName: "projects/402866575973/secrets/gws_client_secret/versions/1"
    env: gws_client_secret
  - versionName: "projects/402866575973/secrets/gauth_admin_password/versions/1"
    env: "gws_ops_pass_encr"
  - versionName: "projects/402866575973/secrets/gauth_admin_password/versions/1"
    env: "gauth_admin_password"
  - versionName: "projects/402866575973/secrets/gauth_admin_password_plain/versions/1"
    env: "gauth_admin_password_plain"
  - versionName: "projects/402866575973/secrets/gauth_admin_username/versions/1"
    env: "gws_ops_user"
  - versionName: "projects/402866575973/secrets/gws_pg_user/versions/1"
    env:  "gws_pg_user"
  - versionName: "projects/402866575973/secrets/gws_pg_pass/versions/1"
    env:  "gws_pg_pass"
  - versionName: "projects/402866575973/secrets/DB_NAME_GWS/versions/1"
    env: "DB_NAME_GWS"
  - versionName: "projects/402866575973/secrets/DB_NAME_PROV/versions/1"
    env: "DB_NAME_PROV"                                      
options:
  logging: CLOUD_LOGGING_ONLY