steps:
- id: 'Provision Pulse Components'
  name: 'gcr.io/gts-multicloud-pe-dev/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-pulse.sh']
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
  timeout: '3600s'
timeout: '3600s'