steps:
- id: 'Provision IWD DM Components'
  name: 'gcr.io/gts-multicloud-pe-dev/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-iwddm.sh']
  timeout: '3600s'
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
timeout: '3600s'