steps:
- id: 'Provision GAUTH Components'
  name: 'gcr.io/gcpe0003/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-gauth.sh']
  secretEnv: ['PULLSECRET','JFROGPASS','JFROGUSR',"deployment_secrets"]
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
  timeout: '3600s'
timeout: '3600s'
availableSecrets:
  secretManager:
  - versionName: "projects/402866575973/secrets/PULLSECRET/versions/1"
    env: 'PULLSECRET'
  - versionName: "projects/402866575973/secrets/JFROGUSR/versions/1"
    env: "JFROGUSR"
  - versionName: "projects/402866575973/secrets/JFROGPASS/versions/1"
    env: "JFROGPASS"
  - versionName: "projects/402866575973/secrets/deployment-secrets/versions/1"
    env: "deployment_secrets"
options:
  logging: CLOUD_LOGGING_ONLY
  #Jira-CPE-4863 