steps:
- id: 'Provision GAUTH Components'
  name: 'gcr.io/gcpe0003/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-gauth.sh']
  secretEnv: ['PULLSECRET']
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
  timeout: '3600s'
timeout: '3600s'
availableSecrets:
  secretManager:
  - versionName: "projects/402866575973/secrets/PULLSECRET"
    env: 'PULLSECRET'