global:
  imagePullSecrets: pullsecret
  imageRegistry: $IMAGE_REGISTRY
  pullPolicy: Always

prometheus:
  podMonitor:
    create: "false"
  alertrule:
    create: "false"

fluent:
  rawlogs:
    stdout:
      enable: "true"
  jsonlogs:
    stdout:
      enable: "true"

tenant:
  logging:
    volume:
      enabled: "false"
      createSC: "false"
      createpvClaim: "true"
      logClaim: "tenant-logs-pvc"
      logClaimSize: "20Gi"
      logStorageClass: "csi-standard-rwx"
      parameters: {}
