apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gauth
stringData:
  POSTGRES_ADDR: pgdb-gws-postgresql.infra
  POSTGRES_USER: 	postgres
  POSTGRES_PASSWORD: secret
  DB_NAME: gauth
  gauth_pg_password: genesys
  gauth_pg_username: genesys
  gauth_redis_password: FPB4d7ynpH
  gauth_admin_password: >-
    $2a$10$7.jOOym2GhhVtpSPXOQmweVqY4gLKOXFbNDRul7UMeP40kQVVx/au
  gauth_admin_password_plain: ops
  gauth_admin_username: ops
  gauth_gws_client_id: external_api_client
  gauth_gws_client_secret: RpV+KfuwZMf+yh7IOJDz+56XgRoBFMExKkycBi7GWNY=
  gauth_jks_keyPassword: Genesys1234 
  gauth_jks_keyStorePassword: Genesys1234
  LOCATION: /USE1